controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Article;
use app\models\Category;
use app\models\Comment;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\Pagination;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $query = Article::find();
        $count = $query->count();
        $pagination = new Pagination(['totalCount'=> $count,'pageSize'=> 1]);
        $articles = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        $popular = Article::find()->orderBy('viewed desc')->limit(3)->all();
        $recent = Article::find()->orderBy('date asc')->limit(5)->all();
        $categories = Category::find()->all();
        return $this->render('index',[
            'articles' => $articles,
            'pagination' => $pagination,
            'popular' => $popular,
            'recent' => $recent,
            'categories' => $categories,
        ]);
    }


    /**
     * @param $id Article ID
     */
    public function actionComment($id)
    {
        $comment = new Comment();
        if(Yii::$app->request->isPost){
            $comment->text = Yii::$app->request->post('text');
            $comment->date = Date('Y-m-d');
            $comment->user_id = Yii::$app->user->id;
            $comment->article_id = $id;
            if($comment->saveComment())
                return $this->goBack();
        }

    }

    public function actionBlog($id)
    {
        $article = Article::findOne(['id'=> $id]);
        $popular = Article::find()->orderBy('viewed desc')->limit(3)->all();
        $recent = Article::find()->orderBy('date asc')->limit(5)->all();
        $categories = Category::find()->all();
        $comments = $article->comments;

        return $this->render('blog',[
            'article' => $article,
            'popular' => $popular,
            'recent' => $recent,
            'categories' => $categories,
            'comments' => $comments,
        ]);
    }

    public function actionCategory($id)
    {
        $count = Article::find()->where(['category_id' => $id])->count();
        $pagination = new Pagination(['totalCount'=> $count,'pageSize'=> 1]);
        $articles = Article::find()->where(['category_id' => $id])
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        $popular = Article::find()->orderBy('viewed desc')->limit(3)->all();
        $recent = Article::find()->orderBy('date asc')->limit(5)->all();
        $categories = Category::find()->all();

        return $this->render('category',[
            'articles' => $articles,
            'pagination' => $pagination,
            'popular' => $popular,
            'recent' => $recent,
            'categories' => $categories,
        ]);
    }

    public function geyComments($id)
    {
        $comments = Comment::findAll(['article_id' => $id]);
        return $comments;
    }
}

views/sidebar/sidebar.php
<?php
use yii\helpers\Url;
?>
<div class="col-md-4" data-sticky_column>
    <div class="primary-sidebar">

        <aside class="widget">
            <h3 class="widget-title text-uppercase text-center">Popular Posts</h3>
            <?php foreach ($popular as $post): ?>
                <div class="popular-post">


                    <a href="<?= Url::toRoute(['site/blog','id' => $post->id]);?>" class="popular-img"><img src="<?= $post->getImage();?>" alt="">

                        <div class="p-overlay"></div>
                    </a>

                    <div class="p-content">
                        <a href="#" class="text-uppercase"><?= $post->description;?></a>
                        <span class="p-date"><?= $post->getDate();?></span>

                    </div>
                </div>
            <?php endforeach; ?>
        </aside>
        <aside class="widget pos-padding">
            <h3 class="widget-title text-uppercase text-center">Recent Posts</h3>
            <?php foreach ($recent as $post): ?>
                <div class="thumb-latest-posts">


                    <div class="media">
                        <div class="media-left">
                            <a href="<?= Url::toRoute(['site/blog','id' => $post->id]);?>" class="popular-img"><img src="<?= $post->getImage();?>" alt="">
                                <div class="p-overlay"></div>
                            </a>
                        </div>
                        <div class="p-content">
                            <a href="<?= Url::toRoute(['site/blog','id' => $post->id]);?>" class="text-uppercase"><?= $post->description?></a>
                            <span class="p-date"><?= $post->getDate(); ?></span>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </aside>
        <aside class="widget border pos-padding">
            <h3 class="widget-title text-uppercase text-center">Categories</h3>
            <ul>
                <?php foreach ($categories as $category): ?>
                    <li>
                        <a href="<?= Url::toRoute(['site/category','id' => $category->id]); ?>"><?= $category->title; ?></a>
                        <span class="post-count pull-right"> (<?= $category->getArticles()->count() ?>)</span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </aside>
    </div>
</div>